<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'text'=>'required|min:2|max:50'
        ];
    }
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub

        return[
            'required'=>'The :attribute is required!',
            'min'=>'The :attribute must be long at :min',
            'max'=>'The :attribute must be long at :max'
        ];
    }
}
