<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class KorisnikRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'username'=>'unique:korisnik,KorIme|required|min:3',
            'pass'=>'required|min:8',
            'fSlika'=>'required|mimes:jpg,jpeg,png|max:2000',
            'email'=>'required|email'
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub

        return[
            'required'=>'The :attribute is required!',
            'unique:'=>'The :attribute must be unique',
            'min'=>'The :attribute must be long at :min',
            'mimes'=>'The :attribute must be in form :mimes',
            'email'=>'The :attribute must be a :email'
        ];
    }
}
